---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_method: sudo
  vars:
    lein_download_url: "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    lein_install_path: "/usr/bin/lein"
  roles:
    - role: robertdebock.npm
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
  tasks:
    - name: Download Leiningen.
      get_url:
        url: "{{ lein_download_url }}"
        dest: "{{ lein_install_path }}"
        force: false
        mode: 0755
